### ISSUE TITLE
AttributeError: module 'modules.chat' has no attribute 'get_turn_substrings'

### ISSUE THREAD

**Issue by phr00t** [mamei16/LLM_Web_search#8]
I loaded a 10.7 SOLAR model with llama.cpp. I had it all running on my 8GB RTX 3080 using the "tensorcores" checkbox.

I asked the model "I have 4 apples today. I ate 3 apples yesterday, but none today. How many apples do I have today?"

It responded something kinda dumb, like "Since you have 4 apples today and you ate 3 apples yesterday, you still have the remaining 1 apple from yesterday. Therefore, adding today's 4 apples and the remaining 1 apple, you have a total of 4 + 1 = 5 apples today."

When the text finished, I got this error:

llama_print_timings:        load time =   25133.96 ms
llama_print_timings:      sample time =       2.06 ms /    63 runs   (    0.03 ms per token, 30508.47 tokens per second)
llama_print_timings: prompt eval time =   25133.85 ms /    83 tokens (  302.82 ms per token,     3.30 tokens per second)
llama_print_timings:        eval time =    3455.74 ms /    62 runs   (   55.74 ms per token,    17.94 tokens per second)
llama_print_timings:       total time =   28760.33 ms
Output generated in 29.50 seconds (2.10 tokens/s, 62 tokens, context 83, seed 1180510178)
Traceback (most recent call last):
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\text-generation-webui-main\modules\chat.py", line 364, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "D:\text-generation-webui-main\modules\chat.py", line 332, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "D:\text-generation-webui-main\modules\chat.py", line 275, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt, state, stopping_strings=stopping_strings, is_chat=True, for_ui=for_ui)):
  File "D:\text-generation-webui-main\modules\text_generation.py", line 31, in generate_reply
    for result in _generate_reply(*args, **kwargs):
  File "D:\text-generation-webui-main\modules\text_generation.py", line 81, in _generate_reply
    for reply in generate_func(question, original_question, seed, state, stopping_strings, is_chat=is_chat):
  File "D:\text-generation-webui-main\extensions\llm_web_search\script.py", line 311, in custom_generate_reply
    substring_dict = chat.get_turn_substrings(state, instruct=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.chat' has no attribute 'get_turn_substrings'

**Comment by pmb2** [comment]
yeah, same here.

**Comment by phr00t** [comment]
I think ooba text-generation-webui updated and broke this extension :(

**Comment by AzmodiusX** [comment]
The version that last had that function was snapshot 2023-12-10
Other extensions also broke then as well, including superboogav2

**Comment by bet0x** [comment]
This is the original code:

https://github.com/oobabooga/text-generation-webui/blob/aab0dd962d9f48e9524f8e602f7252a27ed85870/modules/chat.py#L47

`
def get_turn_substrings(state, instruct=False):
    if instruct:
        if 'turn_template' not in state or state['turn_template'] == '':
            template = '<|user|>\n<|user-message|>\n<|bot|>\n<|bot-message|>\n'
        else:
            template = state['turn_template'].replace(r'\n', '\n')
    else:
        template = '<|user|>: <|user-message|>\n<|bot|>: <|bot-message|>\n'

    replacements = {
        '<|user|>': state['name1_instruct' if instruct else 'name1'].strip(),
        '<|bot|>': state['name2_instruct' if instruct else 'name2'].strip(),
    }

    output = {
        'user_turn': template.split('<|bot|>')[0],
        'bot_turn': '<|bot|>' + template.split('<|bot|>')[1],
        'user_turn_stripped': template.split('<|bot|>')[0].split('<|user-message|>')[0],
        'bot_turn_stripped': '<|bot|>' + template.split('<|bot|>')[1].split('<|bot-message|>')[0],
    }

    for k in output:
        output[k] = replace_all(output[k], replacements)

    return output
`

**Comment by AzmodiusX** [comment]
Notably replacing just the code doesn't make it function again, as I tried that myself.

**Comment by mamei16** [comment]
Thanks for reporting this @phr00t and everyone who commented.
 I've now taken a look a the new changes in the chat module and pushed commit 16a6a543ac48f6df5fa3a822a4927b1b22723971, which uses the new `generate_chat_prompt` method in place of the old `get_turn_substrings` that was removed. Try it out and let me know if it works for you too!

**Comment by bet0x** [comment]
@mamei16 Now it is working:

![image](https://github.com/mamei16/LLM_Web_search/assets/778862/f60263bf-a0af-4c4d-955a-9ebc8b65f1d8)

**Comment by mamei16** [comment]
@bet0x Yes, uncheck the "Display search results in chat" option in the LLM Web Search tab

**Comment by bet0x** [comment]
> @bet0x Yes, uncheck the "Display search results in chat" option in the LLM Web Search tab

I'm using the plugin via cli with the API flag so can't uncheck anything :>

**Comment by mamei16** [comment]
I see. Well in that case, open the `settings.json` file in the LLM_Web_search folder and change
```
"display search results in chat": true
```
to
```
"display search results in chat": false
```
and you should be good to go :horse_racing:

**Comment by mamei16** [comment]
Closing this, as the original problem has been fixed :white_check_mark:
